name: FIFA 2026 OFFICIAL AGENT
on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *'
jobs:
  predict:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # Bajamos a 3.11 para máxima compatibilidad con TF y CatBoost
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt --no-cache-dir
      - name: Run Superagent Prediction
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py
